spring:
  application:
    name: pub-sub-web-app
  pulsar:
    client:
      # This client service url uses de "broker" domain name from docker network
      service-url: pulsar://broker:6650

# This port is mapped accordingly to the docker-compose file
server:
  port: 8083